### PR TITLE
Compose v2 build

### PR DESCRIPTION
**Pull request by munkyboy**

### CODE REVIEW

**Comment by paulcichonski** [comment]
What feature is this adding exactly? I can't think of the use case.

**Comment by munkyboy** [comment]
currently, elsy fails if your `docker-compose.yaml` file contains this:
```
my_service:
  build:
    context: <some-dir>
```

**Comment by joeygibson** [comment]
Can you run `gofmt` on the .go files you changed? The formatting is... odd. Some of the indentions seem to be _one space_, instead of a tab.

**Comment by paulcichonski** [comment]
@munkyboy ah gotcha, maybe just add a bbt so we don't break support for that syntax in the future.

**Comment by munkyboy** [comment]
updated changes to adhere to gofmt rules. also modified the test phase to require all source files adhere to gofmt rules.

**Comment by joeygibson** [comment]
I hate the `gofmt` formatting rules, but we should adhere to them. :-)

**Comment by munkyboy** [comment]
I hate them too

**Pull request merged**
